### ISSUE TITLE
What license?

### ISSUE THREAD

**Issue by aimsugita** [devxpy/flutter-keyboard-plugin#1]
Your pubspec page
https://pub.dev/packages/keyboard#-readme-tab-

`unknown (LICENSE)`

What license is it? Is it MIT?

**Comment by devxpy** [comment]
I'm thinking to re-license all projects under LGPL. Does that impose any restrictions on your usage of this library?

**Comment by devxpy** [comment]
Okay, we've made the decision to go with LGPL.
